---
- name: Install multiple packages
  hosts: vms
  become: yes
  vars:
    packages:
      - vim
      - git
      - wget
  tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
      when: ansible_facts.packages[item] is not defined

