---
- name: Install httpd (Apache) on Ubuntu
  hosts: vms
  become: yes
  vars:
    serviceName: "apache2"
  tasks:
    - name: Install Apache HTTP server
      apt:
        name: "{{ serviceName }}"
        state: present
        update_cache: yes

    - name: Start and Enable Apache
      service:
        name: "{{ serviceName }}"
        state: started
        enabled: yes

